// src/pages/Projects.tsx
import { Title } from '@solidjs/meta';
import { For } from 'solid-js';
import projects from '../lib/Projects';
import './Projects.css';

export default function Projects() {
	return (
		<>
			<Title>helge - projects</Title>
			<div class="projectContainer">
				<div class="projects">
					<h1>Projects</h1>
					<p class="note">
						Most projects delivered to customers, or developed and used inhouse are ineglible to be
						listed here, as they are protected under their respective NDA's.
					</p>
					<For each={projects}>
						{(project) => (
							<div class="project">
								<div class="header">
									<h2>{project.title}</h2>
									<div class="techsContainer">
										Tech:
										<div class="techs">
											<For each={project.technologies}>{(tech) => <div>{tech}</div>}</For>
										</div>
									</div>
								</div>
								<p>{project.description}</p>
								<a href={project.url} target="_blank" rel="noopener noreferrer">
									<div class="button">Project url -&gt;</div>
								</a>
							</div>
						)}
					</For>
				</div>
			</div>
		</>
	);
}

// src/routes/projects/+page.svelte
<script>
	import projects from '$lib/Projects';
</script>

<svelte:head>
	<title>helge — Projects</title>
</svelte:head>

<div class="projectContainer">
	<div class="projects">
		<h1>Projects</h1>
		<p class="note">
			Most projects delivered to customers, or developed and used inhouse are ineglible to be listed
			here, as they are protected under their respective NDA's.
		</p>
		{#each projects as project}
			<div class="project">
				<div class="header">
					<h2>
						{project.title}
					</h2>
					<div class="techsContainer">
						Tech:
						<div class="techs">
							{#each project.technologies as tech}
								<div>{tech}</div>
							{/each}
						</div>
					</div>
				</div>
				<p>
					{project.description}
				</p>
				<a href={project.url} target="_blank" rel="noreferrer">
					<div class="button">Project url -></div>
				</a>
			</div>
		{/each}
	</div>
</div>

<style>
	.projectContainer {
		width: 100%;
		max-width: 900px;
		display: flex;
		justify-content: center;
		box-sizing: border-box;
		text-align: center;
		padding: 1em;
		margin: 0 auto;
		text-align: center;
	}

	.note {
		opacity: 0.5;
		margin: 0;
		max-width: 900px;
		text-align: left;
	}

	a {
		text-decoration: none;
	}

	.projectContainer .projects {
		display: grid;
		grid-template-columns: 1fr;
		grid-gap: 40px;
		margin-top: 30px;
	}

	h1 {
		font-weight: 700;
		text-align: start;
	}

	h2 {
		display: flex;
		margin: 0;
	}

	.project {
		text-align: start;
		box-sizing: border-box;
		display: flex;
		flex-direction: column;
		color: white;
		background-color: rgba(0, 0, 0, 0.2);
		-webkit-backdrop-filter: blur(5px);
		backdrop-filter: blur(5px);
		padding: 2rem;
		width: 100%;
		border-radius: 5px;
		transition: transform 0.2s ease-in-out;
		border-radius: 20px;
	}

	.project p {
		font-weight: 100;
		color: rgba(255, 255, 255, 0.7);
		/* color: #708090; */
	}

	.projects {
		width: 100%;
		margin: 50px auto;
		display: grid;
		grid-gap: 1rem;
		grid-template-columns: 1fr;
		margin-bottom: 10px;
	}

	.techsContainer {
		display: flex;
		flex-wrap: wrap;
		gap: 10px;
	}

	.techs {
		display: flex;
		justify-content: space-between;
		align-items: center;
	}
	.techs > div {
		margin: 0 0 0 10px;
	}

	.button {
		display: flex;
		justify-content: center;
		align-items: center;
		/* color: white; */
		color: rgba(255, 255, 255, 0.7);
		border: 2px solid rgba(255, 255, 255, 0.7);
		padding: 10px;
		border-radius: 20px;
	}

	@media (min-width: 900px) {
		.projectContainer {
			padding: 0;
		}
		.projects > h1 {
			font-size: 48px;
			margin: 50px 0 0 0;
		}

		.projects {
			grid-template-columns: 1fr;
		}

		.projects .project {
			min-height: 200px;
		}
		.button {
			max-width: 200px;
		}
	}

	@media (min-width: 600px) {
		.projects {
			grid-template-columns: 1fr;
		}
	}
</style>
