// src/routes/about/+page.svelte
<script>
	import skills from '$lib/Skills';
</script>

<svelte:head>
	<title>helge - about</title>
</svelte:head>

<div class="container">
	<main>
		<h1>About</h1>
		<p>
			I'm is a seasoned software developer with over 15 years of experience. <br />
			My journey in the software field spans years of hands-on experience and a rich background in Software
			Development, Containers and Linux in both large enterprises and small companies, either as a consultant
			or employee.
		</p>
		<h2>Skills</h2>
		{#each Object.entries(skills) as [section, technologies]}
			<ul>
				<li>
					<h4>
						{section}:
					</h4>
					<div class="list">
						{#each technologies as technology}
							<div>
								{technology}
							</div>
						{/each}
					</div>
				</li>
			</ul>
		{/each}
	</main>
</div>

<style>
	.container {
		max-width: 900px;
		padding: 0;
		display: flex;
		justify-content: center;
	}

	main {
		max-width: 100%;
		min-height: 500px;
		text-align: left;
		margin: 0 auto;
		box-sizing: border-box;
	}

	h1 {
		font-weight: 700;
		margin: 0 0 50px 0;
		font-size: 36px;
		text-align: start;
	}

	h2 {
		margin-top: 50px;
	}

	.list {
		display: flex;
		flex-direction: column;
		gap: 30px;
	}

	@media (min-width: 900px) {
		.list {
			flex-direction: row;
		}
		main > h1 {
			font-size: 48px;
		}
	}
</style>

// src/pages/About.tsx
import { Title } from '@solidjs/meta';
import { For } from 'solid-js';
import skills from '../lib/Skills';
import './About.css';

export default function About() {
	return (
		<>
			<Title>helge - about</Title>
			<div class="container">
				<main>
					<h1>About</h1>
					<p>
						I'm is a seasoned software developer with over 15 years of experience. <br />
						My journey in the software field spans years of hands-on experience and a rich background
						in Software Development, Containers and Linux in both large enterprises and small
						companies, either as a consultant or employee.
					</p>
					<h2>Skills</h2>
					<For each={Object.entries(skills)}>
						{([section, technologies]) => (
							<ul>
								<li>
									<h4>{section}:</h4>
									<div class="list">
										<For each={technologies}>{(technology) => <div>{technology}</div>}</For>
									</div>
								</li>
							</ul>
						)}
					</For>
				</main>
			</div>
		</>
	);
}
