// src/components/FrontPage.vue
<template>
  <div class="fade-block">
    <Logo />
    <Person />
    <Links />
    <Button />
  </div>
</template>

<script>
import Logo from "./Logo";
import Person from "./Person";
import Links from "./Links";
import Button from "./Button";

export default {
  name: "Information",
  components: {
    Logo,
    Person,
    Links,
    Button,
  },
};
</script>
<style scoped>
.fade-block {
  opacity: 0;
  animation-delay: 2s;
  animation: fadein 3s ease;
  animation-fill-mode: forwards;
}
@keyframes fadein {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
</style>

// src/components/FrontPage.svelte
<script lang="ts">
  import Logo from './Logo.svelte';
  import Person from './Person.svelte';
  import Links from './Links.svelte';
  import ContactForm from './ContactForm.svelte';

  import { fade } from 'svelte/transition';
</script>

<div in:fade={{ delay: 500 }}>
  <Logo />
  <Person />
  <Links />
  <ContactForm />
</div>
